version: '2'

services:
  main:
    build: .
    ports:
      - "8000:8000"
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db1
    ports:
      - "3306:3306"
