version: '2'

services:
  main:
    build: .
    ports:
      - "80:80"

  db:
    image: hypriot/rpi-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE:   db1
    ports:
      - "3306:3306"

volumes:
  db-data:
