version: '2'

services:
  main:
    build: .
    ports:
      - "80:80"
    restart: always

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE:   db1
